server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movies/**
        - id: STARCAST-SERVICE
          uri: lb://STARCAST-SERVICE
          predicates:
            - Path=/cast/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost